version: "3.3"

services:
  postgres:
      container_name: postgres
      image: postgres:12
      restart: always
      volumes:
      - db_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: books
      ports:
      - "5432:5432"

volumes:
  db_data:
